export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const LOGOUT = 'LOGOUT';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS='PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';

export const PRODUCT_DETAIL_REQUEST = 'PRODUCT_DETAIL_REQUEST';
export const PRODUCT_DETAIL_SUCCESS = 'PRODUCT_DETAIL_SUCCESS';
export const PRODUCT_DETAIL_FAIL = 'PRODUCT_DETAIL_FAIL';

export const PRODUCTS_CATEGORY_REQUEST = 'PRODUCTS_CATEGORY_REQUEST';
export const PRODUCTS_CATEGORY_SUCCESS = 'PRODUCTS_CATEGORY_SUCCESS';
export const PRODUCTS_CATEGORY_FAIL = 'PRODUCTS_CATEGORY_FAIL';

export const CART_ADD_ITEM = 'ART_ADD_ITEM';
export const CART_REMOVE_ITEM = 'ART_REMOVE_ITEM';

