export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const LOGOUT = 'LOGOUT';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const ACTIVATION_REQUEST = 'ACTIVATION_REQUEST';
export const ACTIVATION_SUCCESS = 'ACTIVATION_SUCCESS';
export const ACTIVATION_FAIL = 'ACTIVATION_FAIL';

export const PASSWORD_RESET_REQUEST = 'RESET_PASSWORD_REQUEST';
export const PASSWORD_RESET_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const PASSWORD_RESET_FAIL = 'RESET_PASSWORD_FAIL';

export const PASSWORD_RESET_CONFIRM_REQUEST = 'RESET_PASSWORD_REQUEST';
export const PASSWORD_RESET_CONFIRM_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const PASSWORD_RESET_CONFIRM_FAIL = 'RESET_PASSWORD_FAIL';

export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS='PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';

export const PRODUCT_DETAIL_REQUEST = 'PRODUCT_DETAIL_REQUEST';
export const PRODUCT_DETAIL_SUCCESS = 'PRODUCT_DETAIL_SUCCESS';
export const PRODUCT_DETAIL_FAIL = 'PRODUCT_DETAIL_FAIL';

export const PRODUCTS_CATEGORY_REQUEST = 'PRODUCTS_CATEGORY_REQUEST';
export const PRODUCTS_CATEGORY_SUCCESS = 'PRODUCTS_CATEGORY_SUCCESS';
export const PRODUCTS_CATEGORY_FAIL = 'PRODUCTS_CATEGORY_FAIL';

export const CART_ADD_ITEM = 'ART_ADD_ITEM';
export const CART_REMOVE_ITEM = 'ART_REMOVE_ITEM';
export const CART_SAVE_SHIPPING_ADDRESS = 'CART_SAVE_SHIPPING_ADDRESS';

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST';
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS';
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL';
export const USER_DETAILS_RESET = 'USER_DETAILS_RESET';

export const USER_UPDATE_PROFILE_REQUEST = 'USER_DETAILS_REQUEST';
export const USER_UPDATE_PROFILE_SUCCESS = 'USER_DETAILS_SUCCESS';
export const USER_UPDATE_PROFILE_FAIL = 'USER_DETAILS_FAIL';
export const USER_UPDATE_PROFILE_RESET = 'USER_UPDATE_PROFILE_RESET';

export const CART_SAVE_PAYMENT_METHOD = 'CART_SAVE_PAYMENT_METHOD';