# Generated by Django 4.0.4 on 2022-05-17 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deco_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='user_id',
            new_name='user',
        ),
    ]
