# Generated by Django 4.0.4 on 2022-05-19 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deco_app', '0003_rename_order_id_orderitem_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='payment_method',
            field=models.CharField(choices=[('ramburs', 'Ramburs'), ('card', 'Card')], default=None, max_length=8),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('tablouri', 'Tablouri'), ('copaci', 'Copaci'), ('ceasuri', 'Ceasuri')], default=None, max_length=9),
        ),
    ]
