# Generated by Django 4.0.4 on 2022-05-24 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deco_app', '0004_alter_orders_payment_method_alter_products_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deco_app.orders'),
        ),
    ]
